
"
"options
"
syntax on       
set number "zeilennummern
set incsearch "schon bei eingabe anfangen zu suchen
filetype plugin on
filetype indent plugin on
set ruler<
set expandtab "lehrzeichen statt tabs
set tabstop =2 
set shiftwidth =2 
set hlsearch "suche hervorheben
set showmatch "anzeigen passender klammern etc
set wildmode=longest:list,full "completion on fileopening
set hidden "change buffer without saving
set smartcase "smart case insensitivity
set encoding=iso-8859-1
set cindent
set smartindent
set autoindent


"rechtschreibung

" Rechtschreibung Wörterbücher: ftp://ftp.vim.org/pub/vim/runtime/spell/
set spelllang=de,en     " Mehrere Sprachen
set spellsuggest=5      " Max NN Korrekturen vorschlagen
                        " Cursor auf Wort platzieren und z= eintippen 

"set spell              " Rechtschreibprüfung für alle Dateien einschalten
" oder: nur für bestimmte Dateitypen (Wir aktivieren spell nur für den lokalen
" Buffer)
au BufNewFile,BufRead *.md setlocal spell
"set foldmethod=syntax

map <right> :bn<cr>
map <left> :bp<cr>
nnoremap j gj
nnoremap k gk


"remap escape
"inoremap jk <Esc>
"inoremap kj <Esc>


"nerdtree
"autocmd VimEnter * exe 'NERDTree' | wincmd l "autoopen

"buffer traversal
nnoremap <C-P> :bp <CR>     "previous buffer
nnoremap <C-N> :bn <CR>     "next buffer

"CtrlP
let g:ctrlp_map = '<c-o>' 
let g:ctrlp_working_path_mode = 2

"continue doxygen comments
autocmd FileType c,cpp set comments-=://
autocmd FileType c,cpp set comments+=:///
autocmd FileType c,cpp set comments+=://


"ctags
"set tags=./tags;

"
"abbreviations and commands
"
:ab #p puts "\n\n\n\n\n\n\n\n\n\n\n\n"

"pastemode with simple p
:command PM set paste
:command MP set nopaste

"""""""""""""""""""""""""""""""""""
"remaps
"""""""""""""""""""""""""""""""""""

"since C-a is my prefix for tmux, i have to remap these
nn <C-i> <C-a>

"explorer

let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1

" taglist
nnoremap <silent> <F7> :TagbarToggle<CR> <C-j>
let g:tagbar_autofocus = 1

" nerdtree 
nnoremap <silent> <F8> :NERDTreeToggle <CR>

" Rails
nmap <F11> <Esc>:! ruby -c % 
nmap <F12> <Esc>:Rake<cr>
imap <F12> <Esc>:w<cr>:Rake<cr>


" Edit another file in the same directory as the current file
" " uses expression to extract path from current file's path
" " (thanks Douglas Potts)
 if has("unix")
   map ,e :e <C-R>=expand("%:p:h") . '/'<CR>
 else
   map ,e :e <C-R>=expand("%:p:h") . '\'<CR>
 endif


" functions
"
"
function! MdPreview()
  :! markdown % > /tmp/md_preview.html && firefox  /tmp/md_preview.html
endfunction
command MdPreview call MdPreview()

function! FoldFunctions()
  :%g /function .* {.*$/ normal! $zf%
endfunction
command Fa call FoldFunctions()

set cryptmethod=blowfish
