
"
"options
"
syntax on       
set number "zeilennummern
set incsearch "schon bei eingabe anfangen zu suchen
:filetype indent plugin on
set ruler<
set expandtab "lehrzeichen statt tabs
set tabstop =2 
set shiftwidth =2 
set hlsearch "suche hervorheben
set showmatch "anzeigen passender klammern etc
set wildmode=longest:list,full "completion on fileopening
set hidden "change buffer without saving
"set foldmethod=syntax

" Make me learn the keyboard
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop> 
nnoremap j gj
nnoremap k gk
"tagbar

"nerdtree
"autocmd VimEnter * exe 'NERDTree' | wincmd l "autoopen

nnoremap <C-P> :bp <CR>
vnoremap <C-N> :bn <CR> 

"CtrlP
let g:ctrlp_map = '<c-o>' 
let g:ctrlp_working_path_mode = 2

"continue doxygen comments
autocmd FileType c,cpp set comments-=://
autocmd FileType c,cpp set comments+=:///
autocmd FileType c,cpp set comments+=://


"ctags
"set tags=./tags;

"
"abbreviations and commands
"
:ab #p puts "\n\n\n\n\n\n\n\n\n\n\n\n"
"pastemode with simple p
:command PM set paste
:command MP set nopaste

"""""""""""""""""""""""""""""""""""
"remaps
"""""""""""""""""""""""""""""""""""

"explorer

let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1

" taglist
nnoremap <silent> <F7> :TagbarToggle<CR> <C-j>
let Tlist_GainFocus_on_ToggelOpen = 1 

" nerdtree 
nnoremap <silent> <F8> :NERDTreeToggle <CR>

" Rails
nmap <F11> <Esc>:! ruby -c % 
nmap <F12> <Esc>:Rake<cr>
imap <F12> <Esc>:w<cr>:Rake<cr>


" Edit another file in the same directory as the current file
" " uses expression to extract path from current file's path
" " (thanks Douglas Potts)
 if has("unix")
   map ,e :e <C-R>=expand("%:p:h") . '/'<CR>
 else
   map ,e :e <C-R>=expand("%:p:h") . '\'<CR>
 endif

"moving in buffers"
map <C-h> :bp <CR>
map <C-l> :bn <CR> 

