# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list 'r:|[._-]=** r:|=**' 'r:|[._-]=** r:|=**'
#zstyle :compinstall filename '/home/b.bellee/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory extendedglob
unsetopt beep
bindkey -v

# End of lines configured by zsh-newuser-install
#



setopt noautomenu
setopt auto_list
unsetopt menucomplete
bindkey '^R' history-incremental-search-backward
skip_global_compinit=1

#history up and down
bindkey "\e[A" up-line-or-history
bindkey '\e[B' down-line-or-history

#path
PATH=$PATH:~/bin
JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk-1.7.0/"


#android tools
PATH="$PATH:$HOME/bin/android-sdk-linux/tools"
PATH="$PATH:$HOME/bin/android-sdk-linux/platform-tools"
PATH="$PATH:$HOME/bin/android-sdk-linux/build-tools"

precmd()
{
git_branch=`git branch 2>/dev/null | grep -e '^*' | sed -E 's/^\* (.+)$/(\1) /'`
export git_branch=$git_branch
}
#PS1
setopt promptsubst
setopt PROMPT_SUBST
PS1='(%n@%M)--(%~)--(`date "+%d.%m.%y %H:%M"`)--$git_branch 
[%!]> '


source .commonrc
