# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list 'r:|[._-]=** r:|=**' 'r:|[._-]=** r:|=**'
#zstyle :compinstall filename '/home/b.bellee/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=9999999
SAVEHIST=9999999
setopt appendhistory extendedglob inc_append_history
unsetopt beep

#vimode
bindkey -v
export KEYTIMEOUT=1 # esc delay
bindkey "\e[3~" delete-char

# End of lines configured by zsh-newuser-install
#



setopt noautomenu
setopt auto_list
unsetopt menucomplete
bindkey '^R' history-incremental-search-backward
skip_global_compinit=1

#history up and down
bindkey "\e[A" up-line-or-history
bindkey '\e[B' down-line-or-history

#PS1
autoload -U colors && colors
setopt promptsubst
setopt PROMPT_SUBST
# set VIMODE according to the current mode (default ?[i]?)
precmd()
{
  git_branch=`git branch 2>/dev/null | grep -e '^*' | sed -E 's/^\* (.+)$/(\1) /'`
export git_branch=$git_branch
}
VIMODE='[i]'
function zle-line-init zle-keymap-select 
{
  VIMODE="${${KEYMAP/vicmd/[n]}/(main|viins)/[i]}"
  PS1="%{$fg[magenta]%}(%n@%M)--(%~)(%?)--$git_branch 
[%!]$VIMODE >%{$reset_colors%} "
  zle reset-prompt
}
zle -N zle-keymap-select 
zle -N zle-line-init




source ~/.commonrc
source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
