#!/bin/bash

if  aptitude --version 
then
  PACKAGE_COMMAND="aptitude -y install"
fi

if zypper --version
then
  PACKAGE_COMMAND="zypper -n install"
fi


$PACKAGE_COMMAND zsh 
$PACKAGE_COMMAND pip 
$PACKAGE_COMMAND cmus
$PACKAGE_COMMAND ranger

#zsh-syntax-hihlighting

#dosbox

#newsbeuter

$PACKAGE_COMMAND aajm
$PACKAGE_COMMAND ack-grep
$PACKAGE_COMMAND acl
$PACKAGE_COMMAND angband
$PACKAGE_COMMAND animals
$PACKAGE_COMMAND argyll
$PACKAGE_COMMAND asciijump
$PACKAGE_COMMAND at
$PACKAGE_COMMAND bastet
$PACKAGE_COMMAND bc
$PACKAGE_COMMAND blender
$PACKAGE_COMMAND bombardier
$PACKAGE_COMMAND bsdgames
$PACKAGE_COMMAND bsdmainutils
$PACKAGE_COMMAND bsdutils
$PACKAGE_COMMAND build-essential
$PACKAGE_COMMAND busybox
$PACKAGE_COMMAND bzip2
$PACKAGE_COMMAND calibre
$PACKAGE_COMMAND canto
$PACKAGE_COMMAND cavezofphear
$PACKAGE_COMMAND cli-common
$PACKAGE_COMMAND conky-cli
$PACKAGE_COMMAND coreutils
$PACKAGE_COMMAND cowsay
$PACKAGE_COMMAND crawl
$PACKAGE_COMMAND crda
$PACKAGE_COMMAND curl
$PACKAGE_COMMAND curseofwar
$PACKAGE_COMMAND davfs2
$PACKAGE_COMMAND dc
$PACKAGE_COMMAND ddd
$PACKAGE_COMMAND diffutils
$PACKAGE_COMMAND elinks
$PACKAGE_COMMAND empire
$PACKAGE_COMMAND exuberant-ctags
$PACKAGE_COMMAND fetchmailconf
$PACKAGE_COMMAND fizmo-ncursesw
$PACKAGE_COMMAND fortune
$PACKAGE_COMMAND freepats
$PACKAGE_COMMAND freesweep
$PACKAGE_COMMAND frotz
$PACKAGE_COMMAND funny-manpages
$PACKAGE_COMMAND games-console
$PACKAGE_COMMAND games-tasks
$PACKAGE_COMMAND gcc
$PACKAGE_COMMAND gdb
$PACKAGE_COMMAND gearhead
$PACKAGE_COMMAND gimp-data
$PACKAGE_COMMAND git
$PACKAGE_COMMAND git-core
$PACKAGE_COMMAND git-svn
$PACKAGE_COMMAND glade
$PACKAGE_COMMAND gnuchess
$PACKAGE_COMMAND gnuchess-book
$PACKAGE_COMMAND gnugo
$PACKAGE_COMMAND gnuminishogi
$PACKAGE_COMMAND gnupg
$PACKAGE_COMMAND gpgv
$PACKAGE_COMMAND gpp
$PACKAGE_COMMAND graphviz
$PACKAGE_COMMAND greed
$PACKAGE_COMMAND html2text
$PACKAGE_COMMAND htop
$PACKAGE_COMMAND i3
$PACKAGE_COMMAND imagemagick
$PACKAGE_COMMAND imagemagick-common
$PACKAGE_COMMAND kate
$PACKAGE_COMMAND keepassx
$PACKAGE_COMMAND kmymoney
$PACKAGE_COMMAND logwatch
$PACKAGE_COMMAND markdown
$PACKAGE_COMMAND matanza
$PACKAGE_COMMAND mawk
$PACKAGE_COMMAND moria
$PACKAGE_COMMAND mplayer
$PACKAGE_COMMAND mutt
$PACKAGE_COMMAND nethack-console
$PACKAGE_COMMAND netris
$PACKAGE_COMMAND nettoe
$PACKAGE_COMMAND net-tools
$PACKAGE_COMMAND nmap
$PACKAGE_COMMAND ogamesim
$PACKAGE_COMMAND okular
$PACKAGE_COMMAND omega-rpg
$PACKAGE_COMMAND openssh-client
$PACKAGE_COMMAND openssh-server
$PACKAGE_COMMAND pacman4console
$PACKAGE_COMMAND pandoc
$PACKAGE_COMMAND perl
$PACKAGE_COMMAND perl-base
$PACKAGE_COMMAND perl-modules
$PACKAGE_COMMAND petris
$PACKAGE_COMMAND procmail
$PACKAGE_COMMAND python
$PACKAGE_COMMAND qgit
$PACKAGE_COMMAND rarian-compat
$PACKAGE_COMMAND robotfindskitten
$PACKAGE_COMMAND rsyslog
$PACKAGE_COMMAND ruby
$PACKAGE_COMMAND ruby-dev
$PACKAGE_COMMAND rubygems
$PACKAGE_COMMAND ruby-sqlite3
$PACKAGE_COMMAND saidar
$PACKAGE_COMMAND slashem
$PACKAGE_COMMAND sqlite3
$PACKAGE_COMMAND strace
$PACKAGE_COMMAND subversion
$PACKAGE_COMMAND sudoku
$PACKAGE_COMMAND tig
$PACKAGE_COMMAND tintin++
$PACKAGE_COMMAND tmux
$PACKAGE_COMMAND transmission
$PACKAGE_COMMAND tree
$PACKAGE_COMMAND vifm
$PACKAGE_COMMAND vim
$PACKAGE_COMMAND virt-manager
$PACKAGE_COMMAND virtuoso-minimal
$PACKAGE_COMMAND virtuoso-opensource-6.1-bin
$PACKAGE_COMMAND virtuoso-opensource-6.1-common
$PACKAGE_COMMAND vlc-data
$PACKAGE_COMMAND vlc-nox
$PACKAGE_COMMAND vlc-plugin-pulse
$PACKAGE_COMMAND wamerican
$PACKAGE_COMMAND whiptail
$PACKAGE_COMMAND wine
$PACKAGE_COMMAND wireshark
$PACKAGE_COMMAND xz-utils
$PACKAGE_COMMAND yakuake
$PACKAGE_COMMAND zenity-common
$PACKAGE_COMMAND zgv
$PACKAGE_COMMAND zivot



mkdir ~/src
cd ~/src

#rc_lib
git clobe https://github.com/twist/rc_lib.git ./rc_lib
cd rc_lib && ./setup.sh && cd -

#FZF
git clone https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

pip install mps
pip install mps-youtube

#id3v2
