#!/bin/bash

if [ -z "$TTRSS_SESSION_KEY" ]
then
  answer=`curl -k -d '{"op":"login", "user":"'$TTRSS_USER'", "password":"'$TTRSS_PASSWD'"}'`
 TTRSS_SESSION_KEY=`echo $anser | awk -fs 'content' '{print $2}'`
fi


curl -k -d '{"sid":"ijqamh5j2moq40c5cka20l2a34", "op":"getUnread"}' $TTRSS_URL
